name: tomcat-webapp-demo
vendor: Loïc Minier <loic.minier@ubuntu.com>
version: 1.0
architectures:
 - amd64
services:
 tomcat:
   start: bin/wrapper
   caps:
   - networking
   - network-service
summary: Demo of Tomcat-hosted Webapp
description: This is a demo snap of a Tomcat-hosted webapp produced by snapcraft with maven.
icon: icon.png

parts:
    webapp:
        plugin: maven
        source: git://github.com/lool/snappy-mvn-demo.git
    tomcat:
        plugin: tar-content
        source: http://mirrors.ircam.fr/pub/apache/tomcat/tomcat-8/v8.0.28/bin/apache-tomcat-8.0.28.tar.gz
    local-files:
        plugin: make
        source: .
